### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by duceppemo** [adamewing/methylartist#1]
Hi love the tool! I ran into a few issues using it:
- segmeth wont take absolute paths and it creates an issue at line 1499 when it tries to create the file handle.
- same happens for bam files. if not is the working directory, the samples don't show up in the output tsv and the plots.
- the y axis title of the plots is hardcoded to `mCpG`. My data contains dam information (from nanopolish). The y axis title should adapt synamically to the type of modification. There's already a `--mods` option for segplot. It should be used to adjust the title of the y axis

**Comment by adamewing** [comment]
Glad to hear it's useful or at least useable!

These should be more or less addressed in 1.0.1 - I wasn't able to replicate the issue with .bam files with an absolute path so let me know if you still run into it. The y-axis label for `segplot` output has just been changed to 'modbase' for now... `--mods` is an optional parameter and can also be a comma-delimited list (e.g. if one wanted to compare levels of different modified base motifs), and depending on the input method it often isn't very informative (e.g. if using megalodon models it's generally "m" for 5mCG, "a" for 6mA, etc). I suppose it could be user-specified but I also suspect most users are going to ask for `--svg` output and modify the labels for figures.
