### ISSUE TITLE
.db files, annotation and multiple files.

### ISSUE THREAD

**Issue by Coracollar** [adamewing/methylartist#10]
I’m trying to prepare my data for using methylartist but I’ve encountered a couple things I’m not sure how they should be done. Hope it’s okay if I ask.

1. Is the .db file created by methylartist db-megalodon different from the .db file created by megalodon itself? 
	Also my data has both hmC and mC will methylartist account for that?

2. How do you create MCF7_data_megalodon.txt ? I understand the data_megalodon.txt file will contain all the samples of a experiment so they can be plotted at the same time with methylartist (also I think this is highly related with issue #8)? It would be very useful to have some sort of function to get from an individual .db per sample data to the .txt file used for plotting. 
3. Finally about the -i MCF7_megalodon_annotations.bed, has the megalodon_annotations something special for TE like elements in order to plot them with methylartist? Like some sort of compiling of all elements from one specific type.

**Comment by adamewing** [comment]
Hi, sorry for the delay.

1. No they're not the same, if using .db files you'll need to use one generated by a methylartist function. Note that if you're using megalodon or another tool that outputs the new methylation SAM tags (Mm, Ml) you can use the `modified_bases.bam` file(s) directly via the `-b/--bam` option.

2. See #8 for my anser there or see the example under "segmeth" in the readme. Let me know if you still run into trouble.

3. There's nothing built in or included with methylartist for TEs specifically. If you're studying TEs you can get TE annotations from an external source e.g. the UCSC RepeatMakser track data (contact me outside of github if you're doing this, there are caveats about these annotations).

**Comment by Coracollar** [comment]
Hi,
Thanks, that makes it clear. I just have one last question regarding segmeth. It needs a bed3+2 file of annotations. In you example you use MCF7_megalodon_annotations.bed which I understand is an aggregate of 10kbp beand of CpGs. But it also says it includes promoters, L1HS and SVA. But looking at the file head:
chr1    0       10000   WG_10kbp
chr1    10000   20000   WG_10kbp
chr1    20000   30000   WG_10kbp
It does not seem to have any extra annotations on L1HS, promoters or SVA. Could you explain how did you create the file or what am I missing?  
Thanks,
Cora

**Comment by adamewing** [comment]
Yes, BED3+1 I think (chrom, start, end, annotation). The head of the file shown in the example only shows segments corresponding to the leftmost category on the corresponding `segplot` graphs ("WG_10kbp") which are just genome-wide bins. Later on in the file you'd see annotations corresponding to the other categories which would be labeled accordingly.

**Comment by Coracollar** [comment]
Oooh, that makes sense now! It would be very helpful to know what commands did you use to create the annotation table.

Thanks,
Cora

**Comment by Coracollar** [comment]
I've done segmeth with the following annotations:
head 4vs4_data_megalodon.txt
/path/to/mappings.bam C0_methylartist.db

/path/to/mappings.bam C1_methylartist.db

/path/to/mappings.bam C2_methylartist.db

/path/to/mappings.bam C3_methylartist.db

/path/to/mappings.bam CORT12_methylartist.db

 head annotation.bed 
chr1	0	10000	Whole Genome 10kbp windows
chr1	10000	20000	Whole Genome 10kbp windows
chr1	20000	30000	Whole Genome 10kbp windows
chr1	30000	40000	Whole Genome 10kbp windows
chr1	40000	50000	Whole Genome 10kbp windows
chr1	50000	60000	Whole Genome 10kbp windows
chr1	60000	70000	Whole Genome 10kbp windows
chr1	70000	80000	Whole Genome 10kbp windows
chr1	80000	90000	Whole Genome 10kbp windows
chr1	90000	100000	Whole Genome 10kbp windows


And running the next commands, but I keep having the problem : ValueError: not enough values to unpack (expected 2, got 0)

methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation.bed
2022-04-05 10:45:10,749 starting methylartist with command: /home/coracollar/anaconda3/envs/ame/bin/methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation.bed
Traceback (most recent call last):
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 4450, in <module>
    main(args)
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 4187, in main
    args.func(args)
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 1942, in segmeth
    bam, meth = line.strip().split()
ValueError: not enough values to unpack (expected 2, got 0)

methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation.bed --excl_ambig
2022-04-05 10:46:01,496 starting methylartist with command: /home/coracollar/anaconda3/envs/ame/bin/methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation.bed --excl_ambig
Traceback (most recent call last):
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 4450, in <module>
    main(args)
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 4187, in main
    args.func(args)
  File "/home/coracollar/anaconda3/envs/ame/bin/methylartist", line 1942, in segmeth
    bam, meth = line.strip().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by adamewing** [comment]
I think this was addressed via email, let me know if not.
