### ISSUE TITLE
segmeth output/running time

### ISSUE THREAD

**Issue by Coracollar** [adamewing/methylartist#13]
Hi, I've tried to run segmeth on my data and I'm getting a blank output. Job ends up finishing due to time limit with nothing written to the .tsv table.

Script:
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --time=4-00:00:00
#SBATCH --mem=200G
source ~/anaconda3/etc/profile.d/conda.sh
conda activate ame

methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation_nochr.bed -p 32 --excl_ambig

.out 
2022-04-20 15:40:34,833 starting methylartist with command: /home/coracollar/anaconda3/envs/ame/bin/methylartist segmeth -d 4vs4_data_megalodon.txt -i annotation_nochr.bed -p 32 --excl_ambig
2022-04-20 15:40:35,207 found mod names: m,h
2022-04-20 15:40:35,208 segmeth output filename: annotation_nochr.4vs4_data_megalodon.excl_ambig.segmeth.tsv
slurmstepd: error: *** JOB 35066426 ON spartan-bm018 CANCELLED AT 2022-04-24T15:40:30 DUE TO TIME LIMIT ***

 annotation_nochr.4vs4_data_megalodon.excl_ambig.segmeth.tsv is completely empty.

Shouldn't the program write something in the table while running even if it did not end? Or might it be just a matter of giving more time/more CPUs to the job?

Thanks,
Cora

**Comment by adamewing** [comment]
Hi, segmeth accumulates the results and outputs as a last step (it's multi-threaded, don't want collisions in output) so that's why it leaves an empty file if it crashes.

Some suggestions regarding your slurm job:
Set ntasks to 1
Set cpus-per-task to 32
Your time and memory allocations are probably a bit high unless you have a very large number of sites in `annotation_nochr.bed` (do you?). How large are the regions?
The --excl_ambig option is only if you really want to prevent multi-mapping reads in repeat elements that are likely to be less than the read length. Otherwise it can be detrimental.

**Comment by adamewing** [comment]
Sorry for the delay. Yes, the "of" thing is probably a problem with the table, which seg_start is column 2 you could try something like: `awk '$2=="of" '{print $0}'` to find it.

10020155 lines is quite a lot - what features are you looking at? If you're trying to do whole-genome profiling you should use `wgmeth` instead.

**Comment by Coracollar** [comment]
Hi Adam,
Thanks for your response, I found the source of the problem, some naughty lines with # from the tables I used to do the whole annotation table. 

What is the difference between segmeth and wgmeth? I'm doing some methylation profiling yes, targeting, genes, some transcription factor binding sites, enhancers, promoters, Repeatmaskr tracks and some more. What would be the difference between wgmeth and segmeth? Is wgmeth used for checking differences in methylation distribution between genomic regions? Because I do want to make violin plots, but also compute the statistics for example whether LINE elements have differential methylation as a whole in my treatment.

**Comment by adamewing** [comment]
Sorry (again...) for the delay. You probably want `segmeth` for what you're describing. The `wgmeth` command generates output per-site (e.g. per-CpG) across the entire genome.

For your use case, I would probably recommend seperating the different kinds of annotations into seperate runs based on what all is going to be plotted together, if that makes sense. You can probably fit at most 10-12 categories and still have a legible plot although less is probably better. If you really want one giant table you could still split it up and distribute over a cluster and then concatenate the files together in the end.

**Comment by Coracollar** [comment]
Hi,I will try to separate Thanks. And sorry for the late response too.Also, I have been trying other commands and badly failing at all of them. Apparently I have to many windows for region/locus: methylartist region -d 4vs4_data_megalodon.txt -i 10:86048315-86499356 -g /data/gpfs/projects/punim1048/GRCm38_genome/annotation/allgenescat.gtf --genes Syn3 -l 86236192-86236862,86274400-86274734 -r /data/gpfs/projects/punim1048/GRCm38_genome/genome.fa -n CG --skip_align_plot2022-05-11 16:46:44,006 starting methylartist with command: /home/coracollar/anaconda3/envs/ame/bin/methylartist region -d 4vs4_data_megalodon.txt -i 10:86048315-86499356 -g /data/gpfs/projects/punim1048/GRCm38_genome/annotation/allgenescat.gtf --genes Syn3 -l 86236192-86236862,86274400-86274734 -r /data/gpfs/projects/punim1048/GRCm38_genome/genome.fa -n CG --skip_align_plot2022-05-11 16:46:44,006 locus smaller than 0.5 Mbp, "methylartist locus" may yield better results2022-05-11 16:46:44,176 set window count to 2632022-05-11 16:46:44,176 resetting windows to a minimum of 5002022-05-11 16:46:44,177 motif count: 7902, per window: 152022-05-11 16:46:44,761 using 264 windows normalised for CG content2022-05-11 16:46:44,762 set --smoothwindowsize to 102022-05-11 16:46:44,762 set --modspace to 12022-05-11 16:46:44,764 found mods: h,m2022-05-11 16:46:44,764 using mods h,m2022-05-11 16:46:44,764 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/C0_160921_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:47:57,768 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/C0_160921_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:48:07,015 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/C1_1011921_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:49:09,107 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/C1_1011921_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:49:12,887 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/C2_181121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:50:24,920 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/C2_181121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:50:30,808 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/C3_261121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:50:32,580 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/C3_261121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:50:33,423 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/CORT12_241121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:51:04,733 fetching reads from /data/scratch/projects/punim1048/hmC_scratch/CORT12_241121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:51:05,014 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT13_281021_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:51:49,324 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT13_281021_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:51:50,300 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT14_251121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:52:48,874 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT14_251121_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:52:52,113 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT15_261021_megalodon_5mc_5hmc/mappings.bam.sorted with for mod h2022-05-11 16:53:51,989 fetching reads from /data/gpfs/projects/punim1048/hmC_allmC/CORT15_261021_megalodon_5mc_5hmc/mappings.bam.sorted with for mod m2022-05-11 16:53:55,621 parsing segments (phase None)...2022-05-11 17:03:10,618 100.00 percent of windows for mod h had less than 1 callsgreater than 50.00 windows are uncovered, aborting. How do I solve this?Thanks,Cora   Sent from Mail for Windows From: adamewingSent: Thursday, 19 May 2022 8:48 PMTo: adamewing/methylartistCc: Coracollar; AuthorSubject: Re: [adamewing/methylartist] segmeth output/running time (Issue #13) Sorry (again...) for the delay. You probably want segmeth for what you're describing. The wgmeth command generates output per-site (e.g. per-CpG) across the entire genome.For your use case, I would probably recommend seperating the different kinds of annotations into seperate runs based on what all is going to be plotted together, if that makes sense. You can probably fit at most 10-12 categories and still have a legible plot although less is probably better. If you really want one giant table you could still split it up and distribute over a cluster and then concatenate the files together in the end.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by adamewing** [comment]
I think this was down to having an enormous input for segmeth - sorry wasn't quite sure what to do with this, closing now but happy to try to help if you're still running into issues.
