### ISSUE TITLE
Does methylartist work with bedMethyl?

### ISSUE THREAD

**Issue by YingziZhang-github** [adamewing/methylartist#16]
Hi,
My nanopore methylation sequencing data was generated by R10.3 and thus does not suit for nanopolish, etc. I analysed the data by modbam2bed and got bedMethyl files. Can methylartist work with bedMethyl? Looking forward to your reply. Thank you very much.

**Comment by adamewing** [comment]
Hi, you can use the .bam file with modified base annotations directly via
the -b/--bam option, no need to convert to bedMethyl (unless you also want
to view it on a genome browser).

**Comment by adamewing** [comment]
Inactive conversation, re-open if needed.
