### ISSUE TITLE
local variable 'mm' referenced before assignment

### ISSUE THREAD

**Issue by FraHaa21** [adamewing/methylartist#18]
Hi,

First of all I would like to say that I really like methylartist!
Unfortunately I came across the following error message when using locus:
`Traceback (most recent call last):
  File "/home/franzi/miniconda3/bin/methylartist", line 4794, in <module>
    main(args)
  File "/home/franzi/miniconda3/bin/methylartist", line 4514, in main
    args.func(args)
  File "/home/franzi/miniconda3/bin/methylartist", line 2539, in locus
    mods = mods_methbam(bam)
  File "/home/franzi/miniconda3/bin/methylartist", line 536, in mods_methbam
    mod_strings = mm.split(';')
UnboundLocalError: local variable 'mm' referenced before assignment
`
I used the standalone version of guppy 6.1.7 with remora to generate the modbam files. I merged the files with samtools merge and used clair3 and whatshap for variant calling and haplotagging. I have done the same thing for several runs but I only get the error message for some of them. The others run through the program and the plots look really good.
I used the following command:
`methylartist locus -b gRNA0-neu.sorted.phased.bam -i 21:46096260-46112003 --phased --ref Homo_sapiens.GRCh38.dna.primary_assembly.fa --motif CG --phase_labels 1:WT,2:Mut --ignore_ps --color_by_hp`

Do you have any idea what causes this error and how it can be solved?
Thanks in advance!
Franziska

**Comment by adamewing** [comment]
Hi, someone had a similar issue (I think it must have been an email conversation because I can't fine the issue here) which was caused by a .bam file without the Ml/Mm tags present. Could you double check for the .bam files where it throws this error whether the records have modified base tags (i.e. Ml and Mm tags)? Either way I do need to add better input validation here.

**Comment by FraHaa21** [comment]
Hi, 
Thank you for the fast response!
I checked again and the bam file contains the Mm and Ml tags. I can upload the file somewhere if you want.
The bam files that work and those that don't work were produced with the same commands.

**Comment by FraHaa21** [comment]
@tcb72 Unfortunately, that is not the case here. 

@adamewing : Here is a link to bam files. One that worked and one that did not. The password is the name of this tool.
https://zenger-haarich.quickconnect.to/d/s/pEJlXBlJP0oA5IzM2bTNujYDVkbuFttc/kd6_gz-Dr6Ano7yzncmwvu1_MKh4UwBN-wbGgNM3enwk

**Comment by adamewing** [comment]
@tcb72 thanks for the info regarding primrose, they are actually the correct, it should be MM/ML as of Feb 2022 according to the SAM optional tags spec (https://samtools.github.io/hts-specs/SAMtags.pdf - Appendix A). 

@FraHaa21 thanks for that, will have a look.

**Comment by adamewing** [comment]
Both samples were working with the latest commits so I've put those into a version bump (1.2.3) which should be available on pip (conda will automatically update as well but can take several days).

### working example:

`methylartist locus -b works.sorted.phased.bam -i 21:46096260-46112003 --phased --ref /home/data/ref/ensembl_grch38/Homo_sapiens.GRCh38.dna.primary_assembly.fa --motif CG --phase_labels 1:WT,2:Mut --ignore_ps --color_by_hp`
![works sorted phased 21_46096260_46112003 m phased ms1 smw24 locus meth](https://user-images.githubusercontent.com/1037202/175561125-01bb94c0-7012-4c2f-869a-ceba5491353c.png)

### previously non-working example:

`methylartist locus -b worksnot.sorted.phased.bam -i 21:46096260-46112003 --phased --ref /home/data/ref/ensembl_grch38/Homo_sapiens.GRCh38.dna.primary_assembly.fa --motif CG --phase_labels 1:WT,2:Mut --ignore_ps --color_by_hp`
![worksnot sorted phased 21_46096260_46112003 m phased ms1 smw24 locus meth](https://user-images.githubusercontent.com/1037202/175561242-cfdaa081-d905-4081-bda3-c0e0c1cdb15e.png)

**Comment by FraHaa21** [comment]
Works perfectly! Thank you very much for the fast solution :)
