### ISSUE TITLE
Full set of dependencies not installing?

### ISSUE THREAD

**Issue by starkeynight** [adamewing/methylartist#2]
Hello,

I am attempting to install Methylartist in a virtual environment on my Mac by running `git clone https://github.com/adamewing/methylartist.git`, navigating into the created methylartist directory, then running `python setup.py install`. From here, I am running into an issue where it seems like the full set of dependencies is not installing (specifically ont-fast5-api, possibly others).

Here's what the output looks like: 
`			(venv) user@MacBook-Air methylartist % sudo python setup.py install
			/Users/user/methylation/venv/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
			  warnings.warn(
			running install
			running bdist_egg
			running egg_info
			writing methylartist.egg-info/PKG-INFO
			writing dependency_links to methylartist.egg-info/dependency_links.txt
			writing requirements to methylartist.egg-info/requires.txt
			writing top-level names to methylartist.egg-info/top_level.txt
			reading manifest file 'methylartist.egg-info/SOURCES.txt'
			adding license file 'LICENSE'
			writing manifest file 'methylartist.egg-info/SOURCES.txt'
			installing library code to build/bdist.macosx-10.9-universal2/egg
			running install_lib
			warning: install_lib: 'build/lib' does not exist -- no Python modules to install`
			
			`creating build/bdist.macosx-10.9-universal2/egg
			creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			installing scripts to build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
			running install_scripts
			running build_scripts
			creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
			copying build/scripts-3.9/methylartist -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts
			changing mode of build/bdist.macosx-10.9-universal2/egg/EGG-INFO/scripts/methylartist to 755
			copying methylartist.egg-info/PKG-INFO -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			copying methylartist.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			copying methylartist.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			copying methylartist.egg-info/requires.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			copying methylartist.egg-info/top_level.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
			zip_safe flag not set; analyzing archive contents...
			creating 'dist/methylartist-1.0.5-py3.9.egg' and adding 'build/bdist.macosx-10.9-universal2/egg' to it
			removing 'build/bdist.macosx-10.9-universal2/egg' (and everything under it)
			Processing methylartist-1.0.5-py3.9.egg
			Removing /Users/user/methylation/venv/lib/python3.9/site-packages/methylartist-1.0.5-py3.9.egg
			Copying methylartist-1.0.5-py3.9.egg to /Users/user/methylation/venv/lib/python3.9/site-packages
			methylartist 1.0.5 is already the active version in easy-install.pth
			Installing methylartist script to /Users/user/methylation/venv/bin
			
			Installed /Users/user/methylation/venv/lib/python3.9/site-packages/methylartist-1.0.5-py3.9.egg
			Processing dependencies for methylartist==1.0.5
			Searching for ont-fast5-api
			Reading https://pypi.org/simple/ont-fast5-api/
			Download error on https://pypi.org/simple/ont-fast5-api/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) -- Some packages may not be found!
			Couldn't find index page for 'ont-fast5-api' (maybe misspelled?)
			Scanning index of all packages (this may take a while)
			Reading https://pypi.org/simple/
			Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) -- Some packages may not be found!
			No local packages or working download links found for ont-fast5-api
			error: Could not find suitable distribution for Requirement.parse('ont-fast5-api')
`
Any advice would be greatly appreciated!

**Comment by adamewing** [comment]
Hi, I don't have an OS X system to test on unfortunately. What happens if you try `pip install ont-fast5-api`?

**Comment by adamewing** [comment]
I had a colleague test installing on OS X via `pip install methylartist` which seemed to finish without incident. Closing for now but feel free to re-open if unresolved.
