### ISSUE TITLE
modbam input ?

### ISSUE THREAD

**Issue by colindaven** [adamewing/methylartist#20]
Hi, nice package.

I haven't tried it yet, and probably should have before asking, but it seems like the community or at least Nanopore is moving towards  storing modifications in the modbam format (see megalodon, and https://github.com/epi2me-labs/modbam2bed as well as guppy and their other basecallers).

Because the megalodon db output supported here is huge (roughly 0.5 TB per sample) and the modbam files are only 20-40 GB for my samples, I can't really store and use the DB output.

Are you planning on supporting modbam as an input in future ? Or do you see things differently to how I have interpreted them so far.

Thanks,
Colin

**Comment by adamewing** [comment]
Hi Colin, yes, this is supported by using `--bam` instead of `--data` (should be some examples in the readme, apols the docs aren't well organised). It's been tested with Megalodon, guppy, and I think primrose (pacbio) as well. Let me know if you run into trouble.
