### ISSUE TITLE
ValueError: Could not interpret value `coord` for parameter `x`

### ISSUE THREAD

**Issue by raquelgarza** [adamewing/methylartist#23]
Hi

I'm trying to use methylartist composite for plotting methylation over several SVAs.

I think the software finishes profiling the coordinates, but then it rans into 

```
Traceback (most recent call last):
  File "/sw/pkg/methylartist/1.2.4/bin/methylartist", line 4855, in <module>
    main(args)
  File "/sw/pkg/methylartist/1.2.4/bin/methylartist", line 4570, in main
    args.func(args)
  File "/sw/pkg/methylartist/1.2.4/bin/methylartist", line 4358, in composite
    ax0 = sns.lineplot(x='coord', y='meth', data=meanplot_table, ci='sd', lw=2, hue='sample', palette=sample_color)
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/relational.py", line 692, in lineplot
    p = _LinePlotter(
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/relational.py", line 367, in __init__
    super().__init__(data=data, variables=variables)
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/_core.py", line 605, in __init__
    self.assign_variables(data, variables)
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/_core.py", line 668, in assign_variables
    plot_data, variables = self._assign_variables_longform(
  File "/sw/easybuild/software/Seaborn/0.11.2-foss-2021b/lib/python3.9/site-packages/seaborn/_core.py", line 903, in _assign_variables_longform
    raise ValueError(err)
ValueError: Could not interpret value `coord` for parameter `x`
```

I thought maybe it was because of low methylation calls in the coordinates, so I tried with a subset of coordinates that I've used with `methylartist locus` (finishing succesfully), but it fails with the same error. 

My command is:
`methylartist composite -d methylation_calls_files.txt -s SVA_F.bed -r hg38.fa -p 20 --svg -t SVA_F.cons`

I'm using version 1.2.4

I tried using `--excl_ambig` and to change `-l` to a more loose threshold, but I got the same error.

The contents of methylation_calls_files.txt are:
```
op_043_001.sorted.bam op_043_001_methylation_calls.db
op_043_002.sorted.bam op_043_002_methylation_calls.db
```

Any advice would be greatly appreciated!

Best,

**Comment by adamewing** [comment]
Hi, Sorry to hear it's crashing on you. Could you include the full output including anything before the Traceback, and the first few lines of `SVA_F.bed`?

**Comment by raquelgarza** [comment]
Hi, thank you for the quick response! Of course! Here are the first few lines of SVA_F.bed:

```
chr1    108488347       108490674       SVA_F_dup43     -
chr1    108675095       108676716       SVA_F_dup44     +
chr1    112897625       112899310       SVA_F_dup49     -
chr1    113068817       113070035       SVA_F_dup50     +
chr1    113069789       113071152       SVA_F_dup51     +
chr1    117428797       117431187       SVA_F_dup52     -
chr1    150727945       150729963       SVA_F_dup55     -
chr1    150780850       150782545       SVA_F_dup56     +
chr1    151650596       151652242       SVA_F_dup57     -
chr1    155700508       155701698       SVA_F_dup62     +
chr1    156556909       156557922       SVA_F_dup63     +
chr1    174348481       174351069       SVA_F_dup70     -
chr1    182508683       182510657       SVA_F_dup72     -
chr1    21023240        21024912        SVA_F_dup4      +
chr1    213151489       213153280       SVA_F_dup85     -
```

And here is the full output of composite: 
[850897.composite_SVAs.txt](https://github.com/adamewing/methylartist/files/9459451/850897.composite_SVAs.txt)

**Comment by raquelgarza** [comment]
Hi,

Thank you! This fixed the error :-)

I have some follow up questions that I think are related to what you mention about the SVAs being of different length (I attach a screenshot and annotated it by question number):
1. The line plot from the upper panel seems to start at around position ~80 and finishes at position ~780. The bed file I input only contained entries of >1kbp and my consensus sequence is ~1.5kbp, so I'm confused on to why the methylation % is only calculated from position 80 to 780. Is it because the rest of the positions didn't have that many methylation calls? I just want to make sure it is not the sample legend that is on the way and for some reason stops the plot.
2. Sorry if this is a very noob question, but I see that some of the line plots in the lower panel start as late as position ~440 - is this the result of aligning the sequences from the bed file on to the consensus? in other words, did their start region aligned around position 440 of the consensus?

Best,

<img width="2177" alt="Screenshot 2022-09-08 at 14 52 23" src="https://user-images.githubusercontent.com/31410823/189129578-fec69996-aee3-4535-beb1-b44589a8b626.png">

**Comment by adamewing** [comment]
Q2 probably has to do with the individual TEs' alignment to the consensus, but I have no idea what's going on regarding Q1 on the consensus plot. Will see if I can reproduce with SVA annotations on my end.

**Comment by raquelgarza** [comment]
Ok! Thank you. Just so you know, this plot in particular was with all SVAs of >1kbp.

**Comment by adamewing** [comment]
I see similar results for SVA, it was due to their heterogeneity and an automatic cutoff that determines which sites are included in the mean methylation plot. Because each individual element (in this case SVA) might include different sites (in this case, CG dinucleotides), each position in the reference SVA aligned to the individual SVA in is assessed to see how many SVAs have a CG at that position, call this the "coverage" at that CG. The median coverage is taken across all CGs and used as a cutoff for determining which to include in the plot. Since SVAs are very heterogeneous this doesn't work well so I've added a parameter `--meanplot_cutoff` in [f6f7fee](https://github.com/adamewing/methylartist/commit/f6f7fee39d9212befe79b19dda359175512b113d), let me know if it works for you, looks like this for me (default vs --meanplot_cutoff 5):

default:
![054 data SVA_F 1kbp composite](https://user-images.githubusercontent.com/1037202/191427329-617a9dae-5115-48b7-af29-eaa9edc59e33.png)

`--meanplot_cutoff 5`:
![054 data SVA_F 1kbp meanplot_cutoff_5 composite](https://user-images.githubusercontent.com/1037202/191427381-9c7dcda0-88f3-4cdb-9da8-f848facb72e4.png)

**Comment by raquelgarza** [comment]
Thank you so much! This worked perfectly.

I was wondering - are there matrices I could output to traceback a specific element from the plot? E.g. If I want to know which elements are not methylated towards the end? Or in other words, a matrix that would have the methylation score per position in the consensus? (per element?)

**Comment by adamewing** [comment]
I've added a `--output_table` option to `composite` in commit [737a5c0](https://github.com/adamewing/methylartist/commit/737a5c0a3af796c496917817e52c3c446a133fd4). The output currently looks something like:
```
chrom   start   end     strand  sample  coord   meth
chr16   24108350        24110141        -       054     33      0.6178728620349763
chr2    202534282       202536111       -       054     33      0.90873449102059
chr20   32723118        32724962        +       054     33      0.9506836249230268
... etc ...
```

where `coord` refers to a position in the reference element (.fasta passed to `-t` option). The positions included in the table are determined the same way the positions included in the mean methylation plot (default to median coverage or `--meanplot_cutoff`. Let me know if this works for you.

**Comment by raquelgarza** [comment]
This is so great. Thank you so much!! I'll close this issue now :-)

**Comment by raquelgarza** [comment]
I'm sorry to reopen this. I thought of a related question... 

I tried loading this table to R and plot it as x=coord, y=meth, group =  (chrom+start+end) as a sanity check (it should output the same plot as composite if I understood right).

But I get a much fuller plot: 

<img width="1882" alt="Screenshot 2022-09-29 at 11 06 56" src="https://user-images.githubusercontent.com/31410823/192990530-096a4d1c-5dd4-48aa-b175-0716cd78c609.png">

Here is the code I'm using in R

```
sva_methyl <- fread("methylation_calls.SVA.meanplot_cutoff_5.composite.table.tsv", data.table = F)
sva_methyl$coords_genome <- paste(sva_methyl$chrom, paste(sva_methyl$start, sva_methyl$end, sep="-"), sep=":")
ggplot(sva_methyl, aes(x=coord, y=meth, group = coords_genome)) + geom_line(colour = "steelblue", alpha = 0.5) + theme_classic() 
```

Do you filter this somehow before creating the plots from composite? How can I recreate the plot from the table I got?

Thank you so much again!!

**Comment by adamewing** [comment]
If you haven't tried it, try setting --maxsegs to a value greater than or equal to the number of SVAs in the table.

**Comment by raquelgarza** [comment]
I've tried that, but it still looks quite sparse in comparison.

I'm running 

`methylartist composite -d methylation_calls.txt -s hg38_SVAs_plus1kb.bed -r hg38.fa --svg -t SVA.fa --lenfrac 0.5 --meanplot_cutoff 5 --maxsegs 2400 --output_table`

Where hg38_SVAs_plus1kb.bed has 2326 entries.

**Comment by adamewing** [comment]
Ignore the above comment, I've modified the arguments to `composite` in commit [13522b7](https://github.com/adamewing/methylartist/commit/13522b73564f90158b1fb78325fc8f6c3ad53bf1) so that this makes some sense now I think. There's now a `--minelts` and `--maxelts` which default to 1 and 200, respectively. To plot everything you can just give `--maxelts` a very large value e.g. 5000 e.g.:

```
methylartist composite -d 054.data.txt -s te/SVA.1kbp.bed -r Homo_sapiens_assembly38.fasta -t SVA_F.fa -p 64 --output_table --lenfrac 0.5 --maxelts 5000 -a 0.1
```

![054 data SVA_F 1kbp composite](https://user-images.githubusercontent.com/1037202/193051351-908b221b-52d9-4acf-8b57-bffcc7c0e02c.png)
