### ISSUE TITLE
percent of windows for mod CpG had less than 1 calls greater than 50.00 windows are uncovered, aborting.

### ISSUE THREAD

**Issue by Fatihlrcfs** [adamewing/methylartist#24]
hi @adamewing,

Firstly thank you for providing this package. ı am trying to see whole chromosome methylation for different sample and I used methylartist region -i 22:1-50818468 -d allcombined_data_nanopolish.txt -p 32 -g Homo_sapiens.GRCh38.106.sorted.gtf.gz -n CG -r wholegenome.fasta --skip_align_plot --panelratios 1,0,1,4 --height 4.5 --genepalette viridis --samplepalette viridis but ı get 89.10 percent of windows for mod CpG had less than 1 calls
greater than 50.00 windows are uncovered, aborting.
I have a very small read depth it might cause the error but ı am wondering if is there any way to turn around this. thanks.

**Comment by adamewing** [comment]
You could try setting `--maxuncovered` to 100 but if coverage really is that low the output may not be that useful or representative of reality. Another option with similar caveats would be to try larger values for `-s` (`--smoothwindowsize`) to include more reads per window - the automatically set value will be at the beginning of the terminal output.

**Comment by Fatihlrcfs** [comment]
hi @adamewing  thank you for your advice but ı am getting a different error and ı don't understand why because it pops up even in previous working examples. the error is methylartist database (seg_chrom) does not exist, check that full path is included if not in current working directory. I checked the bed and .tsv file and ı can definitely say that there is seg_chom column in .tsv file I am cofused. thanks

**Comment by adamewing** [comment]
This might be due to the wrong file being passed to -d, could you tell me the command line args & full output?

**Comment by Fatihlrcfs** [comment]
yes ı picked up the wrong file that was my mistake thanks for the answer.:) not .tsv file it should be.txt file ..:(

**Comment by adamewing** [comment]
No worries - presuming this is closable but let me know if you're still having trouble.
