### ISSUE TITLE
methylartist locus y-axis

### ISSUE THREAD

**Issue by partha434** [adamewing/methylartist#26]
Dear adamewing,
Using the methylartist locus command, I have plotted smoothed methylated fraction plot (attached file). How can I change the Y-axis limit (Black circle marked in the attached file) to 0-0.5 instead of 0-1?
![COX1 all_context mtDNA_5403_7140 CpG ms1 smw20 locus meth](https://user-images.githubusercontent.com/108684241/188383516-2864842f-beb2-48cc-bb54-9afd78cb37d5.png)

**Comment by adamewing** [comment]
There's no working option to do that yet but will do shortly.

**Comment by partha434** [comment]
Thank you so much in advance.
Eagerly waiting for it.

**Comment by adamewing** [comment]
fixed in 1.2.5
