### ISSUE TITLE
fast5 does not seem to contain basecalling information

### ISSUE THREAD

**Issue by Fatihlrcfs** [adamewing/methylartist#29]
Hi @adamewing ,

I am working on db generating with guppy(remora) an ı am using  "methylartist db-guppy -s MCF7_ATCC -f fast5_skip/ -p 32 -m [C]G -n 5mC -b age31remoraalignment.sorted.bam -r wholegenome.fasta" command and its start with just below 
2022-09-24 19:22:44,720 mod motif size (--motifsize) = 2 (ensure this is correct for your data)
2022-09-24 19:22:44,724 caching age31remoraalignment.sorted.bam to MCF7_ATCC.bamcache.db
2022-09-24 19:22:50,228 commiting 100000 records to MCF7_ATCC.bamcache.db...
but after 
2022-09-24 19:24:59,115 commiting remaining records to MCF7_ATCC.bamcache.db...
2022-09-24 19:25:00,599 found 565 fast5 files in fast5_skip/
2022-09-24 19:25:00,599 fetching base modifications...
2022-09-24 19:25:01,451 fast5 FAP54305_skip_bf2ff059_415.fast5 does not seem to contain basecalling information
and the end of the analysis is finished but it has been generating a large MCF7_ATCC.bamcache.db. file and guppy.db file. Guppy.db file is just 20 kb and it seems to there is no basecalling info there. how can ı fixed this. I am using 1.2.3 version. thanks

**Comment by adamewing** [comment]
Hi - no need to use `db-guppy` with newer versions of guppy that incorporate remora. I should depreciate this. Instead, use the .bam with modification tags as input to methylartist. The relevant options to `guppy_basecaller` e.g. something like:
```
guppy_basecaller -i your_fast5_directory/ -r -s guppy_output_directory --config /path/to/appropriate/guppy_config_file --device CUDA:0 -a Homo_sapiens_assembly38.fasta --align_type auto --num_alignment_threads 16 --bam_out

ls -1 guppy_output_directory/*.bam > bam_files.txt

samtools merge --write-index -b bam_files.txt merged.bam
```
(the optimal command for your use case may differ)

Then, feed `merged.bam` (or whatever you've named it) to methylartist tools using the `-b` parameter.

**Comment by Fatihlrcfs** [comment]
Hi @adamewing ,
I have a pretty similar guppy basecaller command ı just added --fast5_out  rest of the command same. if I am not misunderstanding you, I can use merge.bam for replacing MCF7_data_megalodon.txt in the command line. thanks for the quick reply

**Comment by adamewing** [comment]
Sorry, could you update to the most recent version (1.2.5) and try again?

**Comment by Fatihlrcfs** [comment]
Hi @adamewing  ,
this is another problem ı am using a university cluster system(Linux based) and when ı search the methylartist with conda search methylartist most current version is 1.2.3. could you offer me how can ıupdate my methylartist to 1.2.5? thanks

**Comment by adamewing** [comment]
Could you please include the full console output and let me know which
version of python you're running?

**Comment by Fatihlrcfs** [comment]
hi @adamewing ,
I am using Python 3.9.13 in my enviroment and here my console coppy 
(methylartist) [2397405@gpu-45 nanopolishcombined]$  methylartist locus -b merged.bam -i 19:56810076-56870725 -l 56835376-56840476 -g Homo_sapiens.GRCh38.106.sorted.gtf.gz --genes PEG3 --slidingwindowsize 20 -s 36 --samplepalette viridis --phased --ref wholegenome.fasta --motif [C]G
2022-09-29 13:12:37,079 starting methylartist with command: /cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist locus -b merged.bam -i 19:56810076-56870725 -l 56835376-56840476 -g Homo_sapiens.GRCh38.106.sorted.gtf.gz --genes PEG3 --slidingwindowsize 20 -s 36 --samplepalette viridis --phased --ref wholegenome.fasta --motif [C]G
2022-09-29 13:12:37,079 motif size (set with --motifsize) 2 does not match length of --motif ([C]G), changed --motifsize
2022-09-29 13:12:37,079 mod motif size (--motifsize) = 4 (ensure this is correct for your data)
2022-09-29 13:12:37,098 phases for bam merged.bam:
Traceback (most recent call last):
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 4933, in <module>
    main(args)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 4645, in main
    args.func(args)
  File "/cluster/lrcfs/ftiras/ftiras_env/envs/methylartist/bin/methylartist", line 2659, in locus
    logger.info('found mods: %s in bam %s' % (','.join(mods), [bam))
TypeError: can only join an iterable
(methylartist) [2397405@gpu-45 nanopolishcombined]$
merge.bam was created with what advice me above but ı could not upload it because of the size issue. thanks

**Comment by adamewing** [comment]
Ah, try "--motif CG", the brackets aren't expected here.

**Comment by Fatihlrcfs** [comment]
Hi @adamewing ,

same error nothing change .:( TypeError: can only join an iterable

**Comment by adamewing** [comment]
Ok, if you look at `merged.bam` with `samtools view merged.bam | less` do you see reads with "MM" and "ML" tags on the ends? If you don't know what I mean happy to explain further - just want to make sure this .bam file actually has the appropriate tags.

**Comment by Fatihlrcfs** [comment]
hi @adamewing ,
here what ı am seeing with your command 
 NM:i:54 cm:i:63 de:f:0.0562     ms:i:555        nn:i:0  s1:i:430        tp:A:S
6dccd62f-f3a3-49f3-8485-34b75ed3b4f0    2048    1       16067   1       27H7M1D5M2D15M4D94M1D6M1D34M2D13M2D24M1D76M1I61M1I98M1D2M1I21M1I18M1D124M1D7M4I2M2D54M1D43M1D27M1D43M1I68M2D20M2I6M3884H        *       0       4790    *       *       AS:i:1454       MD:Z:7^G1G3^GC5C0T0T7^TGTG7G2T13T69^A6^C34^CA13^AG24^G0C8C9C79T116G18^G37A3^G124^A9^CA44G4G4^A2A40^A13G0T2C9^C3G107^CC26
        NM:i:55 SA:Z:6,107001851,-,12S3873M20D905S,60,94;       cm:i:93 de:f:0.0483     ms:i:1466       nn:i:0  s1:i:594        s2:i:607        tp:A:P
8012f3d2-7b6e-4d99-8ad6-1eda0e0e4dcd    272     1       16246   0       13S9M1D14M4D45M1D29M1D24M1D64M1D67M6D137M1D15M2I2M4I16M3D21M1D25M1D19M1I21M1I17M2D7M2D9M1D6M1D50M1I10M1I3M1D43M3D171M2D17M2D7M1I2M1I16M1D42M1D18M1I14M1D24M2D19M1D92M1D3M1I21M1I3M2D8M1I76M1I17M2I70M1D5M2I29M1I4M2D55M1D6M1D11M2I2M1D61M5D5M1D12M1D5M2D8M3I3M2D1M2D3M1D31M2I37M1I51M1I4M1I1M4I11M1D6M1D7M3D68M2D57M1D18M1I15M1D4M1I15M1I3M1D15M1I39M1D8M1D1M1D55M1D6M1I6M1I101M1D2M1D32M1D39M1I56M1D8M1D5M1I16M1D57M1D52M1I12M2D1M1D16M5D3M1D1M2I37M1D5M1I8M2I36M1D19M1D11M1D6M3D11M1I48M2I16M7I21M2I34M1I51M3D23M1I19M1I97M1D2M1D50M1D6M2D3M2D6M1D80M2D27M1D15M2D1M1I18M2D37M1I2M1D16M1D3M1D43M1D60M2D84M5I36M3I34M1D1M1D55M2D73M1D20M2I101M1D4M3D17M3D43M1I4M1I2M1D32M1D56M1I20M1D53M4D7M1D23M3D42M1D15M1D103M1D21M1D30M1D29M3D17M2I14M1D3M1D1M1D72M1I10M1I10M3D2M1D110M1D97M1I6M1D26M1D26M1I6M1D65M1D14M1D56M1I4M2I82M1D27M1D60M1I2M1D35M2D18M1D83M1D48M2D19M2D118M1D23M1I59M1D33M1I13M2D74M5D11M3D12M2D10M2D23M1D50M1D25M2I4M2I27M1I12M1D25M2D32M5D2M1I10M1D3M1I32M1D14M2I12M1I36M2D24M2I1M3D37M1D29M1D56M1I32M2D17M1D20M2D37M3D41M1D18M1I7M3D7M4D1M1D40M1I6M1I17M1D18M2D3M1D23M1D4M1D3M4D5M1I7M7D7M2D13M2D54M2D10M1D64M3I13M1I66M1D15M1D8M2D46M1D27M2D1M1D28M2D6M1D33M1D9M1D90M2I59M1I90M1D62M1D35M3D2M2D27M2D7M1I1M1I7M1D3M1I28M1D11M1I1M1I2M2D5M2D53M1I30M1D224M1D25M2I2M4I9M1D10M3D4M2D15M3D5M1I10M3D3M1D92M1D106M2D3M2D95M27S *       0       7769    *       *       AS:i:12016      MD:Z:9^G14^TTCT24C20^A29^C24^G5G19G0T37^C2T11A16C35^AAAAAT0T0G74T27C32^T33^GGG21^G25^T57^GG7^GT6C2^G6^C1C4C56^T41G1^AAT19A54C0A95^GG17^TG25^G42^T0G31^C24^CT19^G74G0T16^C24G2^CA60C59C10T39^G38^AT55^G6^C13^T56C4^CCTGA5^C1A10^G5^GT1A1T4G2^GC1^GG1C1^T49T24T27T32^T6^G7^TGC23G0C1T41^AT57^G33^G4A17^A9T7T21T14^G8^C1^G0G0G53^G113^C2^G1T0G29^G53C36T4^T3T2C1^G21^G7C0T1C46^C13T9C2T0A0T11T8T14^CC1^G11G0A0T2^TATTT0A2^C1T22C0A0A0G10^C6T27C0T0G12^G19^G11^C6^GTC38C85G56^TTG0T39C98^C2^T50^T2C0C2^TG3^CT2C3^C32C15C0A30^TG23C0A2^G1C13^AT19^GT39^T16^G3^G43^G47G12^AA34C0C101G16^T1^A0A2G51^AA38A34^G21T0A98^T2G1^ATT17^GTG49^C0C13G15T1^G0C0G35T0G37^A7G17C27^TCTT7^G20C2^GGA3C5G5T26^G1C13^T17T85^T2C0A17^C1G0G15T0C10^T29^GAA0G6C23^T1A1^A1^A2T0T50C35A1^CGT2^A2T13G72T20^A103^A1A0A23^A32^T65^A1T1C10^G57T8C0T4C69^G27^A62^G35^GT18^C83^C48^TC19^CT20T97^T64C17^G35C10^CT63G10^GCAAG7C3^GCT3T8^CA3A0G5^CC23^G1C48^C17C1C1T3C0A41^C21C1T1^TG4G0T15C0T9^CTATT7T0A0C2^A0A34^T1T60^AG25^ATT0A1T34^G5A23^T0G87^CA8C0A7^A20^AA37^GAA41^G20C4^ATT7^ATTT1^T2C45C14^T18^CT1T1^G23^G1T2^C3^TAAG9G2^GTGGAGC7^GG13^GT54^GC1T1T1G4^C64A0A77^G15^A8^GC46^A27^GC1^T28^CA6^G33^C9^C98C0G139^T58A3^C1G1G31^AGG2^AC17G0T0G0T6^TG0G9C4^T3C27^G14^GG5^GT6C68A0A0G5^G76G33T0C32T0G0T35G41^T36^A4C5^AAG4^TG15^CCT10C0C1C1^CCG3^T18T73^C33G72^AG3^CA95    NM:i:638        cm:i:686        de:f:0.0606     ms:i:5760       nn:i:0  s1:i:4923       tp:A:S
821bd938-a667-4095-9c35-7ad3b0972221    272     1       16456   0       12S50M1D102M2I26M1I15M1D54M1D8M7D83M1D60M1D10M2D8M1D11M1I24M3I5M2D59M4D79M1D19M2D2M1D84M1D10M1D31M1D92M1D47M2D2M1I36M:
sorry ı don't have too much bioinformatic background. thanks

**Comment by adamewing** [comment]
The above error message is what I get when I try to use a .bam file without modification tags (sorry about that, will make it more informative in the future). It's possible that you ran guppy without a modified base model: what was the `--config` parameter argument when you ran `guppy_basecaller`?

**Comment by Chlo21030409** [comment]
@adamewing I ran guppy with a rerio model (res_dna_r941_min_modbases-all-context_v001.cfg to be exact) to look at 6mA. I used modbam2bed and managed to create a bedmethyl file which contained methylation data so I don't think it's the .bam files?

Thanks

**Comment by Fatihlrcfs** [comment]
Hi @adamewing  and @Chlo21030409 ,
I found the solution to this issue. First I am using the latest version of the guppy (6.3.8) with bam out. during basecalling I added -a and genome.fasta to align the .bam files. Importantly you should pick up the correct configuration for methylation like remora (-c **dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg** ) then merge and sort these bam file into single bam file with `samtools cat outputfolderguppybasecaller/pass/*.bam | samtools sort -o output.sorted_mapped.bam`. After you got the single .bam file, index it with samtools index. this file single.bam file should be wok for all methylartist command with -b.  Each step you can check MM tags with samtools view output.sorted.mapped.bam or runid......0.0.bam

**Comment by adamewing** [comment]
That that's working for you. @Chlo21030409, if you're trying to call 6mA from mod .bams, you'll need the most recent update ([424ddf6](https://github.com/adamewing/methylartist/commit/424ddf654806bbd1cef4d6ac73b806c743d13884)) for this to work properly (even then I'd regard it as experimental).
