### ISSUE TITLE
Seaborn package version check

### ISSUE THREAD

**Issue by Iamyuchiii** [adamewing/methylartist#34]
Hi,
When i use version 0.12.0 of seaborn, the package gives an error code saying that i need version 0.11.2 or later. I found out that the code  which checks the version passes the first if statement but not the second one despite having a higher version https://github.com/adamewing/methylartist/blob/5488bb535d0b208821d3e4c02155ab8c56ccb3de/methylartist#L2534 
Is this an intended action or is it a bug?
Also, thank you for this amazing package!

**Comment by adamewing** [comment]
Yes, sorry, fix is in [ce283a8](https://github.com/adamewing/methylartist/commit/ce283a89544b61aa6b22f673ccc81a87967d41f2)
