### ISSUE TITLE
Custom sample colors in -b mode

### ISSUE THREAD

**Issue by yuliamostovoy** [adamewing/methylartist#40]
Very nice tool! I was wondering if there's a way to customize color per sample in locus or region mode when inputting mod_mappings.bam files rather than db files? The documentation says you can add a color field to the -d input, but when I tried the same with -b, I got this error that suggests that each line should only contain a .bam file and nothing else: 
```
2023-03-14 15:54:43,382 assuming colors.txt contains a list of .bams
bam not indexed: sample1.mod_mapped.bam	#FF0000
```
Is there a way to specify custom colors without .db files that I'm missing? Thanks!

**Comment by adamewing** [comment]
Thanks! There's an undocumented way to do this for `locus` and `region` via putting a `:` between the .bam file name and a colour (hex or something matplotlib/seaborn can understand) e.g. `-b modbam1.bam:#0000FF,modbam2.bam:#00FF00`. That said, It seems reasonable and possible to enable it to be set in a .txt file like how you attempted, will add this.

**Comment by yuliamostovoy** [comment]
Oh, perfect, thank you!

**Comment by adamewing** [comment]
added function in 05538f1
