### ISSUE TITLE
output file / path name

### ISSUE THREAD

**Issue by maxfieldk** [adamewing/methylartist#41]
Hi Adam, thank you so much for this terrific tool.
I am wondering whether there is a way to specify an output file path / name when using segmeth and segplot. Stdout does not do the trick and I couldn't find any function parameter to set.
I use your tool in a snakemake workflow which relies on filename matching to properly execute rules. 
Any help would be greatly appreciated!

**Comment by adamewing** [comment]
Done in [848c7be](https://github.com/adamewing/methylartist/commit/848c7be1cf42d3c02ba3b5ac378c303fbe2e2727), plase follow-up with any issues.

**Comment by maxfieldk** [comment]
Thanks so much Adam!!
