### ISSUE TITLE
motif

### ISSUE THREAD

**Issue by duhuipeng** [adamewing/methylartist#47]
<img width="1138" alt="image" src="https://github.com/adamewing/methylartist/assets/58722433/8afb71b2-8ad6-4551-aa65-98e1c31e1bb5">

Dear author

I see that only bam needs to be provided, but it says that I lack the motif parameter, may I ask where I can get this?

Best

**Comment by sanamkazemi** [comment]
Dear duhuipeng,

Could you please let us know how to get the motifs?

Best

**Comment by adamewing** [comment]
It's the kmer that contains the modification of interest. For example, if you're interested in 5mCpG the motif would be `CG` for all 5mC it'd be `C` for 6mA it'd be `A` etc. Let me know if that doesn't make sense or you run into trouble with it.

**Comment by IanCodes** [comment]
Just to tack on the end of this question: does --motif expect the code used by the sam file spec, e.g. 'h' for 5hmc?
Thank you.

**Comment by adamewing** [comment]
Yes, I think  the one-letter codes are defined by the model you use for dorado/guppy/etc but they'll usually be 'm' for 5mC, 'h' for 5hmC, 'a' for 6mA etc. You can also find them in the .bam file e.g. seeing `MM:Z:C+h?,1007, ... ,C+m?,1007,...` means 'h' and 'm are both valid options for that .bam file.

**Comment by IanCodes** [comment]
@adamewing many thanks for your reply.  Sorry, I am still confused on how to use --mod and --motif.  What would be the example if I was looking for any hemimethylated C?  Is it --mod h --motif C?
