### ISSUE TITLE
Segmeth annotation bed file

### ISSUE THREAD

**Issue by kamungik** [adamewing/methylartist#49]
Hi,
I have modified base called bam files with Mm and Ml tags. As I understood from the posted question-answers, I can directly use the modbam file without creating db through -b option. I want to use the segmeth command. I am confused regarding the -i/intervals parameter. Could you please help how I can get this annotation bed file?

**Comment by adamewing** [comment]
Segmeth compiles methylation stats on a set of intervals, which can be whatever you like (e.g. promoters, LINE elements, cis-regulatory elements, windows across a genome, etc). The `-i/--invervals` option should be followed by a .bed file (BED3+1 works i.e. chromosome, start, end, name).

**Comment by kamungik** [comment]
Thank you for your answer.

**Comment by PanZiwei** [comment]
Hi,
I have a follwing question. I am feeding the segmeth with a annotation file, but the output png is blank. Any idea about the problem? Thank you so much for your help!
My annotation file:
```
(base) [c-panz@sumner-log1 annotation]$ head -10 chr7.promoter_2kb.bed
chr7	54917137	54921137	SEC61G_promoter	-
chr7	54917238	54921238	SEC61G-DT_promoter	+
chr7	54970058	54974058	LOC124901636_promoter	-
chr7	55091321	55095321	LOC643168_promoter	+
chr7	55176842	55180842	LOC105375284_promoter	-
```
