### ISSUE TITLE
Modified-Base calling of pod5 files with Dorado, what's next ?

### ISSUE THREAD

**Issue by 120985** [adamewing/methylartist#54]
I generated modified basecalled bam files with Dorado, i didn't use neither nanopolish or Megalodon.
Do i still need to convert (and how) bam files to a db file ?
How do i launch a command for a locus plot ?
Thanks

**Comment by Qvdauwer** [comment]
Hello,

I had to figure this out as well so I will try to help you,

you can convert a bam output from Dorado using modkit: https://nanoporetech.github.io/modkit/intro_extract.html

with this you can create a .tsv file that can be used to make a db using the costum-db similarly to the deepsignal example on the readme.

Hope this helps

**Comment by itslittman** [comment]
No db file with modbams. You just use the bams as input, no extra steps needed. The MM and ML tags take care of the rest!

noah

**Comment by adamewing** [comment]
@itslittman is correct. Apologies for overlooking this question.
