### ISSUE TITLE
Issue with bam files from guppy

### ISSUE THREAD

**Issue by ccbruels** [adamewing/methylartist#57]
I basecalled using  guppy 6.5.7 dna_r10.4.1_e8.2_400bps_modbases_5mc_cg_sup.cfg, and used samtools cat to cat and then index the bam files. Those bam files work with other downstream packages.

I tried running methylartist and got this:
$ methylartist locus -i chr1:161449001-161450000 --ref GRCh38.fa --motif C --primary_only -b 001-021.modmapped.bam,113-01.modmapped.bam
  File "/home/pkang/shared/software/methylartist/methylartist", line 2877
    sys.exit(f'unparsable line in {args.bams}: {line.strip()}')
                                                             ^
SyntaxError: invalid syntax

I also tried the test data and got the same error:
methylartist locus -d MCF7_data_megalodon.txt -i chr7:1072064-1101499 -g Homo_sapiens.GRCh38.97.chr.sorted.gtf.gz --genes GPER1 -l 1085667-1089471 -p 1,6,1,3,4
  File "/home/pkang/shared/software/methylartist/methylartist", line 2877
    sys.exit(f'unparsable line in {args.bams}: {line.strip()}')
                                                             ^
SyntaxError: invalid syntax

Is there something else I need to do?

**Comment by adamewing** [comment]
Sorry for the delay, could you let me know what version of python you're running this with (`python --version`)? My suspicion is that you might be using an older version that doesn't support f-strings.

**Comment by adamewing** [comment]
See #59
