### ISSUE TITLE
syntax error when running methylartist

### ISSUE THREAD

**Issue by blackwidowst** [adamewing/methylartist#59]
Hello,

After installing methylartist, we are getting this error:

methylartist --help
File "/usr/local/methylartist/1.2.7/bin/methylartist", line 2862
sys.exit(f'unparsable line in {args.bams}: {line.strip()}')
^
SyntaxError: invalid syntax

**Comment by adamewing** [comment]
Could you let me know which version of python you're running? My suspicion is it's an earlier version prior to support for f-strings. (ref #57)

**Comment by blackwidowst** [comment]
That was it, thank you.  A later version of python worked.

**Comment by adamewing** [comment]
Ok, great!
