### ISSUE TITLE
Error violin plots

### ISSUE THREAD

**Issue by DominicGuanzon** [adamewing/methylartist#60]
Hello,

Thanks for all your effort into methylartist.

I get the following error when running segplot with -v option.  Without the -v option segplot works fine.

################################################################################
File "/home/user/Programs/miniconda3/envs/Companion_diagnostic/bin/methylartist", line 5522, in <module>
    main(args)
  File "/home/user/Programs/miniconda3/envs/Companion_diagnostic/bin/methylartist", line 5210, in main
    args.func(args)
  File "/home/user/Programs/miniconda3/envs/Companion_diagnostic/bin/methylartist", line 2665, in segplot
    sns_plot = sns.violinplot(x='sample', y='modbase', data=plot_data, hue='group', dodge=True, jitter=True, hue_order=order, palette=args.palette)

...

AttributeError: PolyCollection.set() got an unexpected keyword argument 'jitter'
################################################################################

I believe the lines below are the problem, sns.violinplot has not argument called jitter.

https://github.com/adamewing/methylartist/blob/7b48512613eb054d49469ff5172be32134252108/methylartist#L2678-L2680

**Comment by adamewing** [comment]
Fixed in [6d6044e](https://github.com/adamewing/methylartist/commit/6d6044e8aee225d30272b1bc20c3a09ce8d7bbd2), sorry for the delay.
