### ISSUE TITLE
Invalid script entry point when installing `methylartist==1.2.8`

### ISSUE THREAD

**Issue by PanZiwei** [adamewing/methylartist#63]
Hi,
I am trying to install the `methylartist` but encoutered the error below. Do you have any idea to oslve the issue? Thanks!
FYI, I am using `Python 3.12.0`.
```
conda create -n methylartist -c anaconda
conda activate methylartist

conda install pip
pip install methylartist

ERROR: For req: methylartist==1.2.8. Invalid script entry point: <ExportEntry methylartist = methylartist:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```
Update: Everything is fine when I downgraded to `methylartist==1.2.7`, but the error is specific to `methylartist==1.2.8`

**Comment by adamewing** [comment]
Apologies, this was a packaging error due to me not understanding pyproject.toml properly - should be fixed in 1.2.11. Note that I have build issues with python 3.12 due to bx-python, testing with python 3.10 works.

**Comment by PanZiwei** [comment]
Thanks for the quick check! It seems that the version on pip installation is not updated? See below.
```
(methylartist) [c-panz@sumner030 result]$ pip install methylartist==1.2.11
(methylartist) [c-panz@sumner030 result]$ methylartist --version
methylartist 1.2.10
```

**Comment by adamewing** [comment]
Ah yea, I just neglected to update the version in the script: https://github.com/adamewing/methylartist/blob/863b01e79ec136bc9fdb18a5cdf799595344a950/methylartist#L5280

Will fix on next update.
