### ISSUE TITLE
BAM file checking

### ISSUE THREAD

**Issue by mattloose** [adamewing/methylartist#69]
Hi,

Great tool! Thank you!

Couple of minor quirks. The code at present tests for the presence of a bam index file but does so by assuming the bam index is in the bai format and not the more recent csi - however, the csi file type does work with methylartis and so should be probably be allowed in the code as standard?

In addition, whilst the code checks for the presence of the index file, it doesn't actually check that the bam file itself is present in the user specified location. Thus if the user passes an incorrect path you get the warning "bam index not found" when in fact the path is incorrect.

Apologies for not submitting a pull request to fix this.

Thanks

**Comment by adamewing** [comment]
Thanks for this and apologies for the delay - should be fixed in 8e1cd69ef7b762fb2a368c2584bf625bb99a8126 and 9757a12345f1250518a0b1578c9fd79cf6cc819c

--Adam
