### ISSUE TITLE
segplot x-axis limit?

### ISSUE THREAD

**Issue by itslittman** [adamewing/methylartist#70]
Is it possible to limit the x-axis with segplot?

**Comment by adamewing** [comment]
The horizontal axis would be controlled by the genome coordinates, but if you mean the vertical axis then there are options for `--ymin` and `--ymax` to control this.

**Comment by itslittman** [comment]
@adamewing I mean the ridge plots for genome-wide methylation. 5hmC is a very small percentage of the genome; while the peaks are all right near the 0 mark, the X-axis goes all the way to 0.4, making it impossible to visualize small differences.

**Comment by adamewing** [comment]
Ah, yes, I've added functionality to apply `--min` and `--max` (formerly `--ymin` and `--ymax`) to ridge plots in https://github.com/adamewing/methylartist/commit/1835b482db1b8c3287fc5f79757ccea1d576bbba.
