### ISSUE TITLE
question with plot between 'gene model' and  'translation from genome to CpG-only coordinate space' ?

### ISSUE THREAD

**Issue by lovenlong** [adamewing/methylartist#73]
Dear all, 

I'm trying to explore CpG methylation profiles across chromosomes of a genome assembly by using the `region `  option and I got the expected plots. 
```
methylartist region  -o chr* -i chr*:start-end  -d db.txt -r genome.chr.fa -n CG -g gene_model.gtf.gz -p 100 \
--samplepalette magma  --highlightpalette viridis --skip_align_plot --panelratio 1,0,1,4 --height 4.5
```

But I couldn't find a description for the plot between the 'gene model' and the 'translation from genome to CpG-only coordinate space'.  Could somebody help to explain it clearly?
Thank you!

Best,
Wenlong
 
![chr1](https://github.com/adamewing/methylartist/assets/44828353/50e7f229-81b2-4756-975a-03cacdc270dd)

**Comment by adamewing** [comment]
Hi Wenlong,

The modified base space, in this case "CG-space" is just the genome with everything that isn't a motif sequence removed (in this case, everything that isn't a "CG" is removed). The order of bases is conserved, and there is a translation between the genome coordinates and this new sequence, which is what's shown in the "translation" panel. The reason for doing this is for visualisation purposes as there is no data over anything that isn't a "CG". Let me know if this makes sense!

**Comment by adamewing** [comment]
feel free to reopen if that wasn't clear.
