### ISSUE TITLE
Issue methylartist locus

### ISSUE THREAD

**Issue by OceaneMion** [adamewing/methylartist#76]
Hi all,
I have the following error do you have an idea of what is wrong with my data ?

![image](https://github.com/adamewing/methylartist/assets/111916472/e90f39e9-2031-45d6-8c67-9e0254f262a8)

Thanks in advance for your awnser

**Comment by adamewing** [comment]
This looks like a malformed gtf/gff line, the attribute field should be "A semicolon-separated list of tag-value pairs, providing additional information about each feature." per the gtf/gff spec (https://asia.ensembl.org/info/website/upload/gff.html).

**Comment by OceaneMion** [comment]
Yes thank you I instead used a .bed file like you mentionned.
