### ISSUE TITLE
Saving plots into pdf

### ISSUE THREAD

**Issue by Machadum** [adamewing/methylartist#79]
Hi,

Is there a way to save the plots in .pdf instead of .png? If yes could you indicate the option to do this?

Thanks!

**Comment by adamewing** [comment]
Not PDF directly, but it can do .svg output via `--svg` and then could convert to PDF of that will do?

**Comment by Machadum** [comment]
Thank you for the speedy answer! Last question: is there a way to only plot 5mC and not 5hmC (and vice-versa) using methylartist locus --bams?

**Comment by adamewing** [comment]
yes, for only 5mC use `-m m` where -m is --mods which specifies which mods to collect (so for 5hmC only it'd be -m h).

**Comment by Machadum** [comment]
Great thank you! Very last question, I am working with bam files with GenBank chromosomes IDs (e.g. chromosome 1: CM000663.1 · chromosome 2: CM000664.1 ...). While using methylartist locus my --ref is  GCA_000001405.14_GRCh37.p13_genomic_fornanovar.fna but now if I specify --gtf Homo_sapiens.GRCh37.87.clean.gtf.gz to get the gene models it does not work. 
This is the command I tried:
methylartist locus --bams /Volumes/Raspoutine/Barrès_lab/GeckoTEk/Pilot_Toulouse_2023-08-18/output/Pilot_Toulouse_2023-08-18_bam_pass_merged_sorted.bam,/Users/mildrude/Desktop/20240415_GeckoTEk_SLiTE7-2_PAW04469_pass.sorted.bam -i CM000680.1:58038000-58040050 -g /Volumes/Raspoutine/Ext.datasets/References/Homo_sapiens.GRCh37.87.clean.gtf.gz --genes MC4R --ref /Volumes/Raspoutine/Ext.datasets/References/GCA_000001405.14/ncbi_dataset/data/GCA_000001405.14/GCA_000001405.14_GRCh37.p13_genomic_fornanovar.fna --motif CG --samplepalette viridis --labelgenes --svg
and this is the error I get:
2024-05-21 15:47:55,352 building genes plot...
Traceback (most recent call last):
  File "/Users/mildrude/opt/anaconda3/bin/methylartist", line 5755, in <module>
    main()
  File "/Users/mildrude/opt/anaconda3/bin/methylartist", line 5427, in main
    args.func(args)
  File "/Users/mildrude/opt/anaconda3/bin/methylartist", line 3383, in locus
    genes = build_genes(gtf, chrom, elt_start, elt_end, tx=args.show_transcripts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mildrude/opt/anaconda3/bin/methylartist", line 1676, in build_genes
    for line in gtf.fetch(chrom, start, end):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pysam/libctabix.pyx", line 507, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region 'CM000680.1:58038001-58040050'

How could I fix it?

**Comment by adamewing** [comment]
Does `Homo_sapiens.GRCh37.87.clean.gtf.gz` use the same chromosome/contig naming scheme as your reference genome?

**Comment by Machadum** [comment]
I think it does not and that may be the reason why.

**Comment by adamewing** [comment]
I think this can be closed.
