### ISSUE TITLE
Is There an Option to Hide or Resize the Legend in methylartist?

### ISSUE THREAD

**Issue by evalopezf** [adamewing/methylartist#80]
Hi, 

I am currently using methylartist version 1.3.0 for my genomic data analysis. I've encountered an issue where the legend for sample data in the visualizations takes up a substantial amount of space. This sometimes obscures important data or makes the visualization cluttered.
I attempted to use the `--hidelegend` option, assuming it might hide , but it appears not to work.
I was wondering if there is an option to either hide the legend or adjust its size.
Also, is there any possibility of editing the labels of the legend to make them more concise or informative?

Thank you for developing such a useful tool.

Best regards, Eva.

![Example Output](https://github.com/adamewing/methylartist/assets/153935665/f80ea1ad-169b-40ce-b899-f15a6636cf51)

**Comment by mllamasl** [comment]
Hi Eva,

I’ve encountered the same issue and, unfortunately, I don’t believe that option is currently available. However, one solution that worked for me was running methylartist with the `--svg` option. This allows you to open and manipulate the image in programs like Inkscape.

I hope this helps!

Best,
María

**Comment by adamewing** [comment]
Sorry haven't been able to figure this one out, `--hidelegend` is what you should be using. Could either of you or anyone else with this problem post the command line arguments you're using?

**Comment by YoungMatizzle** [comment]
Hi All! 

I'm having the same issue over here, this is the command I am using (simplified):

methylartist locus -i NC_046382.1:8746698-8763250 --motif CG --primary_only --mods m --ref GCF_011125445.2_MU-UCD_Fhet_4.1_genomic.fna --labelgenes --hidelegend --gtf sorted.gtf.gz -b sample1.bam,sample2.bam
....
usage: methylartist [-h] [-v] {db-nanopolish,db-megalodon,db-custom,db-guppy,db-sub,segmeth,segplot,locus,region,composite,wgmeth,adjustcutoffs,scoredist} ...
methylartist: error: unrecognized arguments: --hidelegend

**Comment by adamewing** [comment]
Apologies, that'll be because `--hidelegend` was in the main branch but not released, this and other changes have been packaged into 1.3.1, could you upgrate methylartist, verify that it's 1.3.1 via `methylartist -v` and retry?

**Comment by YoungMatizzle** [comment]
Hi Adam,

This worked!! Thank you so much!!!!

Tia

From: adamewing ***@***.***>
Date: Thursday, September 19, 2024 at 12:58 AM
To: adamewing/methylartist ***@***.***>
Cc: Tia Colwell ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [adamewing/methylartist] Is There an Option to Hide or Resize the Legend in methylartist? (Issue #80)

Apologies, that'll be because --hidelegend was in the main branch but not released, this and other changes have been packaged into 1.3.1, could you upgrate methylartist, verify that it's 1.3.1 via methylartist -v and retry?

**Comment by mllamasl** [comment]
Hi everyone!

I was also using an older version of methylartist (1.3.0), which might have been the reason I encountered the issue. After upgrading to 1.3.1 as Adam suggested, it worked perfectly.

Thanks again for the help!

Best,
María

**Comment by adamewing** [comment]
OK, great! Will close but happy to repoen if still not working for OP.
