### ISSUE TITLE
Change the position of the sample name

### ISSUE THREAD

**Issue by njaupan** [adamewing/methylartist#9]
Hi Love this tool !!!

I just found out that the sample name is the same as the bam file name, I would like to ask 
1) How can I change the position of the sample name or allow not to show it?

2) For the annotation file, is it possible to choose to show transposable elements without exons from gtf?

**Comment by njaupan** [comment]
Hello.
I just found out that the sample name is the same as the bam file name, so I changed the bam file.
Now I would like to ask 

1) How can I change the position of the sample name or allow not to show it?

2) For the gtf annotation file, is it possible to choose to show transposable elements without exons?

**Comment by adamewing** [comment]
Hi, thanks for your enthusiasm regarding methylartist!

1. I would recommend outputting the image as a vector graphic (`--svg`) and then moving or removing the sample name(s) in Illustrator/Inkscape/Affinity Design/etc.

2. Right now for something to show up in the gene track it needs a `gene_id`, and a `gene_name` attribute. If it doesn't have any exone it'll just show up as a line which probably isn't what you want. If you want to display custom data this way I would make sure it has those two attributes and call it an exon. Additional annotation display options (e.g. via a BED file) are a feature I'm planning on adding very soon so if it's not urgent I hope this will be much easier within a few weeks.

**Comment by adamewing** [comment]
Closing old issues, Should also note that `--bed` was added some time ago.
