### ISSUE TITLE
What are the pale regions in the smoothed LLR line in `locus`?

### ISSUE THREAD

**Issue by skranz0** [adamewing/methylartist#90]
When using `methylartist locus`, there are sometimes regions in the smoothed LLR track that are of a paler color, as in the attached image. What do those mean?
![linus_P5CS_1A](https://github.com/user-attachments/assets/bd0f4d21-3f91-4431-bb0b-cdfa8eba3381)

**Comment by adamewing** [comment]
Those correspond to regions where coverage is low. By default the threshold is 1 read (as in your orange sample). It's controlled by `--maskcutoff` and can be turned off via `--nomask`.

**Comment by skranz0** [comment]
Okay, that makes sense. Thanks for the quick reply!
