### ISSUE TITLE
Highlighting a region breaks the `locus` plot

### ISSUE THREAD

**Issue by skranz0** [adamewing/methylartist#91]
Maybe I'm doing something wrong here, but with `methylartist locus` get this nice plot
![linus_BADH_6B](https://github.com/user-attachments/assets/5c0cc482-92b6-4fdd-b327-a9f17f6cc6aa)

But when I add ` -l 690453000-69045400` to the same command, it looks like this
![linus_V1W0 chr6B_690452054_690463469 m cohort ms1 smw24 locus meth](https://github.com/user-attachments/assets/7323ed9e-86fd-49aa-8773-1e8a50f0daee)

Obviously there's something going wrong. Can someone help locate the issue?

**Comment by adamewing** [comment]
You're missing a zero on the end coord of 690453000-69045400.

This should have hit a check for the highlight being out of range though so it's something I need to check on, thanks!

**Comment by skranz0** [comment]
Oh I really was! I double checked if I had a typo, but apparently can't count. Nice that it was still helpful

**Comment by adamewing** [comment]
Fixed in 1.3.1.
